# Module 3: Data Structures Assignments
## Lesson 3.3: Sets
### Assignment 1: Creating and Accessing Sets

Create a set with the first 10 positive integers. Print the set.

### Assignment 2: Adding and Removing Elements

Add the number 11 to the set created in Assignment 1. Then remove the number 1 from the set. Print the modified set.

### Assignment 3: Set Operations

Create two sets: one with the first 5 positive integers and another with the first 5 even integers. Perform and print the results of union, intersection, difference, and symmetric difference operations on these sets.

### Assignment 4: Set Comprehensions

Create a new set containing the squares of the first 10 positive integers using a set comprehension. Print the new set.

### Assignment 5: Filtering Sets

Create a new set containing only the even numbers from the set created in Assignment 1 using a set comprehension. Print the new set.

### Assignment 6: Set Methods

Create a set with duplicate elements and remove the duplicates using set methods. Print the modified set.

### Assignment 7: Subsets and Supersets

Create two sets: one with the first 5 positive integers and another with the first 3 positive integers. Check if the second set is a subset of the first set and if the first set is a superset of the second set. Print the results.

### Assignment 8: Frozenset

Create a frozenset with the first 5 positive integers. Print the frozenset.

### Assignment 9: Set and List Conversion

Create a set with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a set. Print the resulting set.

### Assignment 10: Set and Dictionary

Create a dictionary with set keys and integer values. Print the dictionary.

### Assignment 11: Iterating Over Sets

Create a set and iterate over the elements, printing each element.

### Assignment 12: Removing Elements from Sets

Create a set and remove elements from it until it is empty. Print the set after each removal.

### Assignment 13: Set Symmetric Difference Update

Create two sets and update the first set with the symmetric difference of the two sets. Print the modified first set.

### Assignment 14: Set Membership Testing

Create a set and test if certain elements are present in the set. Print the results.

### Assignment 15: Set of Tuples

Create a set containing tuples, where each tuple contains two elements. Print the set.

In [ ]:
#Assignment 1: Creating and Accessing Sets
#Create a set with the first 10 positive integers. Print the set.

set1=set(range(1,11))
print(set1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
#Assignment 2: Adding and Removing Elements
#Add the number 11 to the set created in Assignment 1. Then remove the number 1 from the set. Print the modified set.

set1.add(11)
set1.remove(1)

print(set1)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [ ]:
#Assignment 3: Set Operations
#Create two sets: one with the first 5 positive integers and another with the first 5 even integers.
#Perform and print the results of union, intersection, difference, and symmetric difference operations on these sets.

set2=set(range(1,6))
set3=set(range(2,11,2))
print(f" Set 1 : {set2} and set 2 : {set3}")
print(f" Union of {set2} and {set3} : {set2.union(set3)}")
print(f" Intersection of {set2} and {set3} : {set2.intersection(set3)}")
print(f" Difference of {set2} and {set3} : {set2.difference(set3)}")
print(f" Symmetric Difference of {set2} and {set3} : {set2.symmetric_difference(set3)}")


#another way to do same :
"""
print(f"Union: {set1 | set2}")
print(f"Intersection: {set1 & set2}")
print(f"Difference (set1 - set2): {set1 - set2}")
print(f"Symmetric Difference: {set1 ^ set2}")
"""

 Set 1 : {1, 2, 3, 4, 5} and set 2 : {2, 4, 6, 8, 10}
 Union of {1, 2, 3, 4, 5} and {2, 4, 6, 8, 10} : {1, 2, 3, 4, 5, 6, 8, 10}
 Intersection of {1, 2, 3, 4, 5} and {2, 4, 6, 8, 10} : {2, 4}
 Difference of {1, 2, 3, 4, 5} and {2, 4, 6, 8, 10} : {1, 3, 5}
 Symmetric Difference of {1, 2, 3, 4, 5} and {2, 4, 6, 8, 10} : {1, 3, 5, 6, 8, 10}

In [ ]:
#Assignment 4: Set Comprehensions
#Create a new set containing the squares of the first 10 positive integers using a set comprehension. Print the new set.

set4={i**2 for i in range(1,11)}
print(set4)

{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}

In [ ]:
#Assignment 5: Filtering Sets
#Create a new set containing only the even numbers from the set created in Assignment 1 using a set comprehension. Print the new set.

set5={i for i in set1 if i%2==0}
print(set5)

{2, 4, 6, 8, 10}

In [ ]:
#Assignment 6: Set Methods
#Create a set with duplicate elements and remove the duplicates using set methods. Print the modified set.

set6={1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10}
unique=set(set6)
print(unique)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
#Assignment 7: Subsets and Supersets
#Create two sets: one with the first 5 positive integers and another with the first 3 positive integers.
#Check if the second set is a subset of the first set and if the first set is a superset of the second set. Print the results.

s7=set(range(1,6))
s8=set(range(1,4))
print(f"set 1 : {s7}")
print(f"set 2 : {s8}")
print(f"set 2 is subset of  set 1?   ans :  {s8.issubset(s7)}")
print(f"set 1 is superset of set 2 ?   ans :  {s7.issuperset(s8)}")

set 1 : {1, 2, 3, 4, 5}
set 2 : {1, 2, 3}
set 2 is subset of  set 1?   ans :  True
set 1 is superset of set 2 ?   ans :  True

In [ ]:
#Assignment 8: Frozenset
#Create a frozenset with the first 5 positive integers. Print the frozenset.
"""
A frozenset in Python is a built-in set type that is immutable, meaning that once it is created, its elements cannot be changed, added, or removed.
This is in contrast to a regular set, which is mutable and allows modifications.

Characteristics of frozenset :
Immutable: You cannot modify the elements of a frozenset after it has been created.
Hashable: Because it is immutable, a frozenset can be used as a key in a dictionary or as an element in another set.
Unordered: Like regular sets, frozensets do not maintain any order of elements
"""

s9=frozenset(range(1,6))
print(s9)

frozenset({1, 2, 3, 4, 5})

In [ ]:
#Assignment 9: Set and List Conversion
#Create a set with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a set. Print the resulting set.

s10=set(range(1,6))
s10=list(s10)
s10.append(6)
s10=set(s10)
print(s10)
print(type(s10))

{1, 2, 3, 4, 5, 6}
<class 'set'>

In [ ]:
#Assignment 10: Set and Dictionary
#Create a dictionary with set keys and integer values. Print the dictionary.

s11={
    frozenset({1,2}) : 1,
    frozenset({3,4}) : 2,
    frozenset({5,6}) : 3
   }

print(s11)

{frozenset({1, 2}): 1, frozenset({3, 4}): 2, frozenset({5, 6}): 3}

In [ ]:
#Assignment 11: Iterating Over Sets
#Create a set and iterate over the elements, printing each element.

s12 = set(range(1,6))

for s in s12 :
  print(s)

1
2
3
4
5

In [ ]:
#Assignment 12: Removing Elements from Sets
#Create a set and remove elements from it until it is empty. Print the set after each removal.

s13=set(range(1,11))
print(f"Original Set : {s13}")
for i in range(len(s13)):
  s13.pop()
  print(f" Set afet {i+1} removal : {s13}")

Original Set : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
 Set afet 1 removal : {2, 3, 4, 5, 6, 7, 8, 9, 10}
 Set afet 2 removal : {3, 4, 5, 6, 7, 8, 9, 10}
 Set afet 3 removal : {4, 5, 6, 7, 8, 9, 10}
 Set afet 4 removal : {5, 6, 7, 8, 9, 10}
 Set afet 5 removal : {6, 7, 8, 9, 10}
 Set afet 6 removal : {7, 8, 9, 10}
 Set afet 7 removal : {8, 9, 10}
 Set afet 8 removal : {9, 10}
 Set afet 9 removal : {10}
 Set afet 10 removal : set()

In [ ]:
#Assignment 13: Set Symmetric Difference Update
#Create two sets and update the first set with the symmetric difference of the two sets. Print the modified first set.

s14 =set(range(1,8))
s15 =set(range(4,11))

s14.symmetric_difference_update(s15)
print(s14)

{1, 2, 3, 8, 9, 10}

In [ ]:
#Assignment 14: Set Membership Testing
#Create a set and test if certain elements are present in the set. Print the results.

s16 =set(range(1,6))
print(3 in s16)
print(0 in s16)
print(7 in s16)
print(5 in s16)

True
False
False
True

In [ ]:
#Assignment 15: Set of Tuples
#Create a set containing tuples, where each tuple contains two elements. Print the set.

s17={
    (1,2),
    (4,5),
    (7,8)
}

print(s17)

{(4, 5), (1, 2), (7, 8)}